routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
   //return redirect()->route('login');
});

Auth::routes();

Route::post('/search',array('as'=>'ser','uses'=>'FormController@search'));
Route::post('/eve',array('as'=>'eve','uses'=>'FormController@eventSearch'));
Route::get('/evet/{id}',array('as'=>'evet','uses'=>'FormController@evet'));
Route::get('/evet2/{id}',array('as'=>'evet2','uses'=>'FormController@evet2'));
Route::get('/showResults/{id}', array('as' => 'showResults', 'uses' => 'FormController@showResults'));
Route::get('/addAdmin', array('as' => 'addAdmin', 'uses' => 'FormController@addAdmin'));
Route::post('/register', array('as' => 'register', 'uses' => 'FormController@register'));
Route::get('/adminList', array('as' => 'adminList', 'uses' => 'FormController@adminList'));
Route::delete('/deleteAdmin/{id}', array('as' => 'deleteAdmin', 'uses' => 'FormController@destroyAdmin'));
Route::get('/unconfirmed', array('as' => 'unconfirmed', 'uses' => 'FormController@unconfirmed'));
Route::post('/confirm/{id}', array('as' => 'confirm', 'uses' => 'FormController@confirm'));
Route::get('/home', 'FormController@index');
//Route::post('print', 'PrintController', array('only'=>array('show1')));

Route::resource('form','FormController');
Route::resource('event','EventController');
Route::resource('attachment', 'AttachmentsController');
Route::resource('print', 'PrintController', array('only'=>array('show')));
Route::resource('otr', 'OTRController', array('only'=>array('show')));

Route::resource('coach','CoachController');
Route::resource('ce','CEventsController');
Route::resource('gallery','GalleryController');
Route::resource('cl','CheckController');
Route::resource('masterlist', 'MasterListController');

resources/views/adminList.blade.php
<?php
	use App\User;
?>

@extends ('layouts.app')

@section ('content')
	<div class="row">
		<script>
            function ConfirmDelete()
            {
                var x = confirm("Are you sure you want to delete?");
                if (x)
                    return true;
                else
                    return false;
            }
        </script>
		@forelse($admins as $admin)
			@if($admin->userType == "admin")
				<div class="col-md-4 col-md-offset-4">
					<div class="panel panel-default">
						<div class="panel-heading">
							{{$admin->faculty_id}}
						</div>
						<div class="panel-body">
							{{$admin->fullName}}
						</div>
						<div class="panel-footer clearfix" style="background-color: white;">
							@if($admin->id == Auth::id())
								@if(User::where('userType', 'admin')->count() > 1)
									{{Form::open(['route' => ['deleteAdmin', $admin->id], 'method' => 'DELETE', 'onsubmit' => 'return ConfirmDelete()'])}}
									{{csrf_field()}}
									<button type="submit" class="btn btn-danger btn-sm">Delete</button>
									{{csrf_field()}}
									{{Form::close()}}
								@endif
							@endif
						</div>
					</div>
				</div>
			@endif
		@empty
			No Admin. Really? How'd you get in?!
		@endforelse
	</div>
@endsection

resources/views/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        @if(count($errors)>=1)
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-8">
                    @foreach($errors->all() as $e)
                        <span class="help-block">{{$e}}</span>
                    @endforeach
                </div>
            </div>
            <br>
        @endif
        <script>
            function ConfirmCreate()
            {
                var x = confirm("Are you sure of the information you entered?");
                if (x)
                    return true;
                else
                    return false;
            }
        </script>
        {{ Form::open(array('url'=>route('form.store'), 'method'=>'POST', 'files'=>'true', 'onsubmit' => 'return ConfirmCreate()')) }}
        {{ csrf_field() }}
            <div class="row">
                <div class="col-md-8">
                    &nbsp;
                </div>
                <div class="col-md-2">&nbsp;</div>
                <div class="col-md-2">
                    <div class="form-group">
                        {{ Form::label('Upload Image') }}
                        {{ Form::file('image', null, array('class'=>'form-control')) }} 
                    </div>
                </div>
            </div>
            <br>
                <div class="row">
                    <div class="form-group">
                        <div align="center"><h1>Student Information</h1></div>
                        <br/>
                        <br/>
                        <div class="col-md-2">{{ Form::label('Student Number') }}</div>
                        <div class="col-md-3">
                            {{ Form::text('student_number',null,array('class'=>'form-control', 'placeholder'=>'Student Number')) }}
                        </div>
                        <div class="col-md-1">
                            {{ Form::label('SCUAA Category') }}
                        </div>
                        <div class="col-md-3">
                            {{ Form::select('scuaaCategory', array(1 => 'Regional', 2 => 'National'), null, array('class'=>'form-control')) }}
                        </div>
                      <!--  <div class="col-md-1">{!! Form::label('Event') !!}</div>
                        <div class="col-md-3">
                            {!! Form::select('event',$events->pluck('desc','id'), null, ['class' => 'form-control']) !!}
                        </div>-->
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="form-group">
                        <div class="col-md-2">{{ Form::label('Name') }}</div>
                        <div class="col-md-3">
                            {{ Form::text('lname', null, array('class'=>'form-control', 'placeholder'=>'Last Name')) }}
                        </div>
                        <div class="col-md-3">
                            {{ Form::text('fname', null, array('class'=>'form-control', 'placeholder'=>'First Name')) }}
                        </div>
                        <div class="col-md-3">
                            {{ Form::text('mname', null, array('class'=>'form-control', 'placeholder'=>'Middle Name')) }}
                        </div>
                    </div>
                </div>
                <br>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-2">{{ Form::label('Birth date') }}</div>
                    <div class="col-md-2">
                        {{ Form::date('dob', \Carbon\Carbon::now(), array('class'=>'form-control')) }}
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-2">
                        
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-2">{{ Form::label('Password') }}</div>
                    <div class="col-md-2">
                        <input id="password" type="password" class="form-control" name="password" required>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-2">
                        
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-2">{{ Form::label('Address') }}</div>
                    <div class="col-md-4">
                        {{ Form::text('address',null,array('class'=>'form-control','placeholder'=>'Address')) }}
                    </div>
                    <div class="col-md-1">{{ Form::label('Contact #') }}</div>
                    <div class="col-md-4">
                        {{ Form::text('contact', null, array('class'=>'form-control', 'placeholder'=>'Contact Number')) }}
                    </div>
                </div>
            </div>
            <br/>
            <div class="row">
                <div class="form-group">
                    <div align="center"><h1>Medical Information</h1></div>
                    <br/>
                    <br/>
                    <div class="col-md-2">{{ Form::label('Weight') }}</div>
                    <div class="col-md-2">
                        {{ Form::text('weight', null, array('class'=>'form-control', 'placeholder'=>'Weight')) }}
                    </div>
                    <div class="col-md-1">{{ Form::label('Height') }}</div>
                    <div class="col-md-2">
                        {{ Form::text('height', null, array('class'=>'form-control', 'placeholder'=>'Height')) }}
                    </div>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-2">{{ Form::label('Blood Type') }}</div>
                    <div class="col-md-1">
                        {{ Form::text('blood_type', null, array('class'=>'form-control', 'placeholder'=>'Type')) }}
                    </div>
                    <div class="col-md-1">{{Form::label('Allergies')}}</div>
                    <div class="col-md-3">
                        {{Form::text('allergies',null,array('class'=>'form-control','placeholder'=>'Allergies'))}}
                    </div>
                    <div class="col-md-1">{{Form::label('Medication if Any')}}</div>
                    <div class="col-md-3">
                        {{Form::text('medication',null,array('class'=>'form-control','placeholder'=>'Medication'))}}
                    </div>
                </div>
            </div>
        <br>
        <br>
        <div class="row">
           <div class="col-md-4">&nbsp;</div>
            <div class="col-md-6"><h1>Educational Background</h1></div>
        </div>
        <br>
        <div class="row">
            <div class="col=md-12">
                <table class="table">
                    <thead>
                        <td>&nbsp;</td>
                        <td>Name of School</td>
                        <td>Year Graduated</td>
                    </thead>
                   <tr>
                       <td>Elementary</td>
                       <td>{{Form::text('elementary[name]',null,array('class'=>'form-control', 'placeholder'=>'Elementary School Name'))}}</td>
                       <td>{{Form::text('elementary[year]',null,array('class'=>'form-control', 'placeholder'=>'Year Graduated (e.g. 2010)'))}}</td>
                   </tr>
                    <tr>
                        <td>High School</td>
                        <td>{{Form::text('high[name]',null,array('class'=>'form-control', 'placeholder'=>'High School Name'))}}</td>
                        <td>{{Form::text('high[year]',null,array('class'=>'form-control', 'placeholder'=>'Year Graduated (e.g. 2014)'))}}</td>
                    </tr>
                </table>
            </div>
        </div>
        <br>
        <br>
        <div class="row">
            <div class="col=md-12">
                <div align="center"><h1>Course Information</h1></div>
                <br/>
                <table class="table">
                    <tr>
                        <td>Course and Year</td>
                        <td>{{Form::text('col[name]',null,array('class'=>'form-control', 'placeholder'=>'Course and Year (e.g. BSCS III)'))}}</td>
                        <td>{{Form::text('col[year]',null,array('class'=>'form-control', 'placeholder'=>'Year Graduated (e.g. 2018)'))}}</td>
                    </tr>
                    <tr>
                        <td>If Transfereee Specify</td>
                        <td>{{Form::text('trans[name]',null,array('class'=>'form-control', 'placeholder'=>'Name of School Transferred From'))}}</td>
                        <td>{{Form::text('trans[year]',null,array('class'=>'form-control' , 'placeholder'=>'Year Transferred (e.g. 2017)'))}}</td>
                    </tr>
                </table>
            </div>
        </div>
        <br>

        
        <div class="row">
            <div class="col-md-10">&nbsp;</div>
            <div class="col-md-2">
                {{Form::submit('Save', array('class' =>' btn btn-success'))}}
            </div>
        </div>
        {{csrf_field()}}
        {{Form::close()}}
    </div>
@endsection

resources/views/evet.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if(\Illuminate\Support\Facades\Session::has('messages'))
            <div class="row">
                <div class="col-md-2">&nbsp;</div>
                <div class="col-sm-8 alert alert-danger">
                    <center><span >{{\Illuminate\Support\Facades\Session::get('messages')}}</span></center>
                </div>
            </div>
        @endif
        <div class="row">
            {{Form::open(array('url'=>route('eve'),'method'=>'POST'))}}
            {{csrf_field()}}
            <div class="form-group"></div>
            <div class="col-md-4" align="left">
                {{Form::select('events_id',$events->pluck('desc','id'),$id,array('class'=>'form-control'))}}
            </div>
            <div class="col-md-2">
                {{Form::submit('Go',array('class'=>'btn btn-success'))}}
            {{csrf_field()}}
            {{Form::close()}}
            </div>
			
            <div class="col-md-2">&nbsp; </div>
        </div>

        <div class="row">&nbsp; </div>
		<?php
            $counter = 1;
        ?>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-responsive table-condensed">
                    <thead>
					<td>Number</td>
                    <td>Student Number</td>
                    <td>Name</td>
                    <td>&nbsp;</td>
                    </thead>
                    <script>
                        function ConfirmDelete()
                        {
                          var x = confirm("Are you sure you want to delete?");
                          if (x)
                            return true;
                          else
                            return false;
                        }
                    </script>
					
                    @foreach($info as $i)
						@if(!is_object($i->info))
							@continue;
						@endif
						
                        <tr>
                            <td>{{ $counter }}</td>
							<td>{{$i->info->student_number}}</td>
                            <td class="text-uppercase">{{$i->info->lname}},{{$i->info->fname}} {{$i->info->mname}}</td>
                            <td width="3">

                                {{Form::open(array('url'=>route('form.edit', Crypt::encrypt($i->info->student_number)) ,'method'=>'GET'))}}
                                {{csrf_field()}}
                                
                                <button type="submit" class="glyphicon glyphicon-edit"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                            <td width="3">
                                {{Form::open(array('url'=>route('form.destroy',$i->info->student_number) ,'method'=>'DELETE', 'onsubmit' => 'return ConfirmDelete()'))}}
                                {{csrf_field()}}
                                
                                <button type="submit" class="glyphicon glyphicon-trash"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                            <td width="3">
                                {{Form::open(array('url'=>route('print.show',$i->info->student_number) ,'method'=>'GET'))}}
                                {{csrf_field()}}
                                
                                <button type="submit" class="glyphicon glyphicon-print"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                            <td width="3">
                                {{Form::open(array('url'=>route('otr.show',$i->student_number) ,'method'=>'GET'))}}
                                {{csrf_field()}}
                                <button type="submit" class="glyphicon glyphicon-user"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                        </tr>
						<?php
							$counter += 1;
						?>
                    @endforeach
                </table>

            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-10" align="right">{{ $info->links() }}</div>
        </div>

        <div class="uk-container uk-container-center" style="margin-top: 15px;">
            <div class="uk-grid">
                <div class="uk-width-1-1 uk-visible-large">
                    <div class="uk-border-rounded" style="background-color: #006e1b; padding: 8px; color: #FFF; margin-bottom: 25px;">
                        <img src="/images/mmsu.png" alt="" width="50">
                        &nbsp;
                        Copyright {{\Carbon\Carbon::now()->format('Y')}} by MMSU ITC and CHuMs
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/evet2.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if(\Illuminate\Support\Facades\Session::has('messages'))
            <div class="row">
                <div class="col-md-2">&nbsp;</div>
                <div class="col-sm-8 alert alert-danger">
                    <center><span >{{\Illuminate\Support\Facades\Session::get('messages')}}</span></center>
                </div>
            </div>
        @endif
        
        <div class="row">&nbsp; </div>

        <div class="row">
            <div class="col-md-12">
                <table class="table table-responsive table-condensed">
                    <thead>
                    <td>Student Number</td>
                    <td>Name</td>
                    <td>&nbsp;</td>
                    </thead>
                    <script>
                        function ConfirmDelete()
                        {
                          var x = confirm("Are you sure you want to delete?");
                          if (x)
                            return true;
                          else
                            return false;
                        }
                    </script>
                    @foreach($info as $i)
                    @if(!is_object($i->info))
                        @continue;
                    @endif
                        <tr>
                            <td>{{$i->info->student_number}}</td>
                            <td class="text-uppercase">{{$i->info->lname}},{{$i->info->fname}} {{$i->info->mname}}</td>
                            <td width="3">

                                {{Form::open(array('url'=>route('form.edit', Crypt::encrypt($i->info->student_number)) ,'method'=>'GET'))}}
                                {{csrf_field()}}
                                
                                <button type="submit" class="glyphicon glyphicon-edit"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                            <td width="3">
                                {{Form::open(array('url'=>route('form.destroy',$i->info->student_number) ,'method'=>'DELETE', 'onsubmit' => 'return ConfirmDelete()'))}}
                                {{csrf_field()}}
                                
                                <button type="submit" class="glyphicon glyphicon-trash"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                            <td width="3">
                                {{Form::open(array('url'=>route('print.show',$i->info->student_number) ,'method'=>'GET'))}}
                                {{csrf_field()}}
                                
                                <button type="submit" class="glyphicon glyphicon-print"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                            <td width="3">
                                {{Form::open(array('url'=>route('otr.show',$i->student_number) ,'method'=>'GET'))}}
                                {{csrf_field()}}
                                <button type="submit" class="glyphicon glyphicon-user"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                        </tr>
                    @endforeach
                </table>

            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-10" align="right">{{ $info->links() }}</div>
        </div>

        <div class="uk-container uk-container-center" style="margin-top: 15px;">
            <div class="uk-grid">
                <div class="uk-width-1-1 uk-visible-large">
                    <div class="uk-border-rounded" style="background-color: #006e1b; padding: 8px; color: #FFF; margin-bottom: 25px;">
                        <img src="/images/mmsu.png" alt="" width="50">
                        &nbsp;
                        Copyright {{\Carbon\Carbon::now()->format('Y')}} by MMSU ITC and CHuMs
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if(\Illuminate\Support\Facades\Session::has('messages'))
            <div class="row">
                <div class="col-md-2">&nbsp;</div>
                <div class="col-sm-8 alert alert-danger">
                    <center><span >{{\Illuminate\Support\Facades\Session::get('messages')}}</span></center>
                </div>
            </div>
        @endif
        <div class="row">
            {{Form::open(array('url'=>route('eve'),'method'=>'POST'))}}
            {{csrf_field()}}
            <div class="form-group"></div>
            <div class="col-md-4" align="left">
                {{Form::select('events_id', $events->pluck('desc','id'),null,array('class'=>'form-control'))}}
            </div>
            <div class="col-md-2">
                {{Form::submit('Go',array('class'=>'btn btn-success'))}}
            </div>
            {{csrf_field()}}
            {{Form::close()}}
            <div class="col-md-2">&nbsp; </div>
            {{Form::open(array('url'=>route('ser'),'method'=>'POST'))}}
            {{csrf_field()}}
            <div class="col-md-2">

                {{Form::text('student_number',null,array('class'=>'form-control','placeholder'=>'Search'))}}

            </div>
            <div class="col-md-2">
                {{Form::submit('Search',array('class'=>'btn btn-success'))}}
                &nbsp;
                <a href="{{ route('form.create') }}" class='btn btn-primary'>Add</a>
            </div>
            {{csrf_field()}}
            {{Form::close()}}
        </div>

        <div class="row">&nbsp; </div>
		
        <div class="row">
            <div class="col-md-12">
                <table class="table table-responsive table-condensed">
                    <thead>
                    <td>Student Number</td>
                    <td>Name</td>
                    <td>&nbsp;</td>
                    </thead>
                    <script>
                        function ConfirmDelete()
                        {
                          var x = confirm("Are you sure you want to delete?");
                          if (x)
                            return true;
                          else
                            return false;
                        }
                    </script>
                    @foreach($info as $i)
                        <tr>
                            
							<td>{{$i->student_number}}</td>
                            <td class="text-uppercase">{{$i->lname}}, {{$i->fname}} {{substr($i->mname,0,1)}}.</td>
							
                            <td width="3">
                            <?php
                                $parameter = $i->student_number;
                                $parameter= Crypt::encrypt($parameter);
                            ?>
                                {{Form::open(array('url'=>route('form.edit', $parameter) ,'method'=>'GET'))}}
                                {{csrf_field()}}
                                <button type="submit" class="glyphicon glyphicon-edit"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                            <td width="3">
                                {{Form::open(array('url'=>route('form.destroy',$i->student_number) ,'method'=>'DELETE', 'onsubmit' => 'return ConfirmDelete()'))}}
                                {{csrf_field()}}
                                <button type="submit" class="glyphicon glyphicon-trash"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                            <td width="3">
                                {{Form::open(array('url'=>route('print.show',$i->student_number) ,'method'=>'GET'))}}
                                {{csrf_field()}}
                                <button type="submit" class="glyphicon glyphicon-print"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                            <td width="3">
                                {{Form::open(array('url'=>route('otr.show',$i->student_number) ,'method'=>'GET'))}}
                                {{csrf_field()}}
                                <button type="submit" class="glyphicon glyphicon-user"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                        </tr>
						
                    @endforeach
                </table>

            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-8" align="center">{{$info->links()}}</div>
        </div>

        <div class="uk-container uk-container-center" style="margin-top: 15px;">
            <div class="uk-grid">
                <div class="uk-width-1-1 uk-visible-large">
                    <div class="uk-border-rounded" style="background-color: #006e1b; padding: 8px; color: #FFF; margin-bottom: 25px;">
                        <img src="/images/mmsu.png" alt="" width="50">
                        &nbsp;
                        Copyright {{\Carbon\Carbon::now()->format('Y')}} by MMSU ITC and CHuMs
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home2.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if(\Illuminate\Support\Facades\Session::has('messages'))
            <div class="row">
                <div class="col-md-2">&nbsp;</div>
                <div class="col-sm-8 alert alert-danger">
                    <center><span >{{\Illuminate\Support\Facades\Session::get('messages')}}</span></center>
                </div>
            </div>
        @endif

        <div class="row">&nbsp; </div>

        <div class="row">
            <div class="col-md-12">
                <table class="table table-responsive table-condensed">
                    <thead>
                    <td>Student Number</td>
                    <td>Name</td>
                    <td>&nbsp;</td>
                    </thead>
                    <script>
                        function ConfirmDelete()
                        {
                          var x = confirm("Are you sure you want to delete?");
                          if (x)
                            return true;
                          else
                            return false;
                        }
                    </script>
                    @foreach($info as $i)
                        <tr>
                            <td>{{$i->student_number}}</td>
                            <td class="text-uppercase">{{$i->lname}}, {{$i->fname}} {{$i->mname}}</td>
                            <td width="3">
                            <?php
                                $parameter = $i->student_number;
                                $parameter= Crypt::encrypt($parameter);
                            ?>
                                {{Form::open(array('url'=>route('form.edit', $parameter) ,'method'=>'GET'))}}
                                {{csrf_field()}}
                                <button type="submit" class="glyphicon glyphicon-edit"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                            <td width="3">
                                {{Form::open(array('url'=>route('form.destroy',$i->student_number) ,'method'=>'DELETE', 'onsubmit' => 'return ConfirmDelete()'))}}
                                {{csrf_field()}}
                                <button type="submit" class="glyphicon glyphicon-trash"></button>
                                {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                            <td>
                                {{Form::open(array('url'=>route('confirm', $i->student_number) ,'method'=>'POST'))}}
                                {{csrf_field()}}
                                    <button type="submit" class="glyphicon glyphicon-ok"></button>
                                    {{csrf_field()}}
                                {{Form::close()}}
                            </td>
                        </tr>
                    @endforeach
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-8" align="center">{{ $info->links() }}</div>
        </div>

        <div class="uk-container uk-container-center" style="margin-top: 15px;">
            <div class="uk-grid">
                <div class="uk-width-1-1 uk-visible-large">
                    <div class="uk-border-rounded" style="background-color: #006e1b; padding: 8px; color: #FFF; margin-bottom: 25px;">
                        <img src="/images/mmsu.png" alt="" width="50">
                        &nbsp;
                        Copyright {{\Carbon\Carbon::now()->format('Y')}} by MMSU ITC and CHuMs
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection