routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
   //return redirect()->route('login');
});

Auth::routes();

Route::post('/search',array('as'=>'ser','uses'=>'FormController@search'));
Route::post('/eve',array('as'=>'eve','uses'=>'FormController@eventSearch'));
Route::get('/evet/{id}',array('as'=>'evet','uses'=>'FormController@evet'));
Route::get('/evet2/{id}',array('as'=>'evet2','uses'=>'FormController@evet2'));
Route::get('/showResults/{id}', array('as' => 'showResults', 'uses' => 'FormController@showResults'));
Route::get('/addAdmin', array('as' => 'addAdmin', 'uses' => 'FormController@addAdmin'));
Route::post('/register', array('as' => 'register', 'uses' => 'FormController@register'));
Route::get('/adminList', array('as' => 'adminList', 'uses' => 'FormController@adminList'));
Route::delete('/deleteAdmin/{id}', array('as' => 'deleteAdmin', 'uses' => 'FormController@destroyAdmin'));
Route::get('/unconfirmed', array('as' => 'unconfirmed', 'uses' => 'FormController@unconfirmed'));
Route::post('/confirm/{id}', array('as' => 'confirm', 'uses' => 'FormController@confirm'));
Route::get('/home', 'FormController@index');
//Route::post('print', 'PrintController', array('only'=>array('show1')));

Route::resource('form','FormController');
Route::resource('event','EventController');
Route::resource('attachment', 'AttachmentsController');
Route::resource('print', 'PrintController', array('only'=>array('show')));
Route::resource('otr', 'OTRController', array('only'=>array('show')));

Route::resource('coach','CoachController');
Route::resource('ce','CEventsController');
Route::resource('gallery','GalleryController');
Route::resource('cl','CheckController');
Route::resource('masterlist', 'MasterListController');

app/Coach.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use Carbon\Carbon;

class Coach extends Model
{
    //
    protected $table='coach';
    protected $fillable=['lname','fname','mname','contact','email','bday','age','address', 'password'];
    public function events(){
        return $this->hasMany('App\CoachEvents','coach_id','id');
    }
    public function age($parameter){
    	return $parameter->diffInYears(Carbon::now());
    }
}

app/_Coach.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Coach extends Model
{
    //
    protected $table='coach';
    protected $fillable=['lname','fname','mname','contact','email','bday','age','address'];
    public function events(){
        return $this->hasMany('App\CoachEvents','coach_id','id');
    }
}

app/Http/Controllers/CoachController.php
<?php

namespace App\Http\Controllers;

use App\Coach;
use App\Events;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;

use App\Http\Requests;
use Illuminate\Support\Facades\Validator;

class CoachController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    } 

    public function index()
    {
        $test = User::where('id', Auth::id())->where('userType', 'admin')->count();
        $test2 = User::where('id', Auth::id())->where('userType', 'coach')->count();

        if($test == 0 && $test2 == 0)
        {
            $shit = User::where('id', Auth::id())->get();
            foreach ($shit as $a) {
                $pass = $a->faculty_id;
            }

            return redirect()->route('form.edit', Crypt::encrypt($pass));
        }
        else
        {
            $info = Coach::orderby('lname', 'ASC')->paginate(20);

            return view('coaches.index', compact('info'));
        }
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $test = User::where('id', Auth::id())->where('userType', 'admin')->count();
        $test2 = User::where('id', Auth::id())->where('userType', 'coach')->count();

        if($test == 0 && $test2 == 0)
        {
            $shit = User::where('id', Auth::id())->get();
            foreach ($shit as $a) {
                $pass = $a->faculty_id;
            }

            return redirect()->route('form.edit', Crypt::encrypt($pass));
        }
        else
            return view('coaches.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $test = User::where('id', Auth::id())->where('userType', 'admin')->count();
        $test2 = User::where('id', Auth::id())->where('userType', 'coach')->count();

        if($test == 0 && $test2 == 0)
        {
            $shit = User::where('id', Auth::id())->get();
            foreach ($shit as $a) {
                $pass = $a->faculty_id;
            }

            return redirect()->route('form.edit', Crypt::encrypt($pass));
        }
        else
        {
            $messages=array(
                'lname.required'=>'Last Name is Required',
                'fname.required'=>'First Name is Required',
            );
            $rules=array(
                'image'=>'required|image',
                'lname'=>'required',
                'fname'=>'required',
                'bday'=>'required',
                'address'=>'required',
				'contact'=>'required',
                'email'=>'required|unique:coach',
                'password'=>'required'
            );
            $validator = Validator::make($request->all(), $rules, $messages)->validate();
            $coach = new Coach();

            if($request->hasFile('image')){
                $d = Carbon::now();
                $name = $request->get('lname').''.$d->day.str_random(4).$d->hour.$d->second;
                $p1 ='\images\\';
                $path = base_path() . '/public/images/';
                $request->file('image')->move($path,$name.'.'.$request->file('image')->getClientOriginalExtension());
                $coach->pic = $p1.$name.'.'.$request->file('image')->getClientOriginalExtension();
            }

            $coach->fill($request->all());
            $shit = Carbon::createFromFormat('Y-m-d', $coach->bday);
            $coach->age = $coach->age($shit);
            $userAthlete = new User();
            $userAthlete->faculty_id = $coach->email;
            $userAthlete->fullName = $coach->fname;
			//$userAthlete->contact = $coach->contact;
            $userAthlete->password = bcrypt($coach->password);
            $userAthlete->userType = "coach";
            $userAthlete->save();
            $coach->save();

            $athletes = Coach::get();

            foreach($athletes as $athlete)
            {
                if((User::where('faculty_id', $athlete->email))->count() >= 1)
                {
                    
                }
                else
                {
                    $userAthlete = new User();
                    $userAthlete->faculty_id = $athlete->email;
                    $userAthlete->fullName = $athlete->fname;
                    $userAthlete->password = bcrypt("admins");
                    $userAthlete->userType = "coach";
                    $userAthlete->save();
                }
            }

            return redirect()->route('coach.edit', $coach->id);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $test = User::where('id', Auth::id())->where('userType', 'admin')->count();
        $test2 = User::where('id', Auth::id())->where('userType', 'coach')->count();
        $events=Events::get();
        $info=Coach::where('id',$id)->get();

        if($info->first()->email == User::where('id', Auth::id())->get()->first()->faculty_id || (User::where('id', Auth::id())->get()->first()->userType == 'admin'))
        {
            if($test == 0 && $test2 == 0)
            {
                $shit = User::where('id', Auth::id())->get();
                foreach ($shit as $a) {
                    $pass = $a->faculty_id;
                }

                return redirect()->route('form.edit', Crypt::encrypt($pass));
            }
            else
            {
                if($info->count()) {
                    $info=$info->first();
                    $e = array();
                    if ($info->events->count()) {
                        foreach ($info->events as $pe) {
                            $e[$pe->name->first()->desc] = $pe->name->first()->desc;
                        }
                    }
                    $shit = Carbon::createFromFormat('Y-m-d', $info->bday);
                    $info->age = $info->age($shit);
                    $info->save();
                    return view('coaches.edit', compact('info', 'events', 'e'));
                } else
                    return redirect()->route('form.index')->with('messages','No Record Found');
            }
        }else if(Auth::check())
        {
            return redirect()->back();
        }
        else
            return redirect()->route('login');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $test = User::where('id', Auth::id())->where('userType', 'admin')->count();
        $test2 = User::where('id', Auth::id())->where('userType', 'coach')->count();

        if($test == 0 && $test2 == 0)
        {
            $shit = User::where('id', Auth::id())->get();
            foreach ($shit as $a) {
                $pass = $a->faculty_id;
            }

            return redirect()->route('form.edit', Crypt::encrypt($pass));
        }
        else
        {
            $messages=array(

                'lname.required'=>'Last Name is Required',
                'fname.required'=>'First Name is Required',
            );
            $rules=array(
                'image'=>'image',
                'lname'=>'required',
                'fname'=>'required',
                'bday'=>'required',
                'address'=>'required',
                'email'=>'required',
				'contact'=>'required',
                'password'=>'required'
                //'password'=>'required'
            );
            $validator=Validator::make($request->all(),$rules,$messages)->validate();
            $coach=Coach::where('id',$id)->get()->first();

            $oldEmail = $coach->email;
            
            if($request->hasFile('image')){
                $d=Carbon::now();
                $name=$request->get('lname').''.$d->day.str_random(4).$d->hour.$d->second;
                $p1='\images\\';
                $path= base_path() . '/public/images/';
                $request->file('image')->move($path,$name.'.'.$request->file('image')->getClientOriginalExtension());
                $coach->pic=$p1.$name.'.'.$request->file('image')->getClientOriginalExtension();
            }
            $coach->fill($request->all());

            $editedAdmin = User::where('faculty_id', $oldEmail)->get()->first();
			$editedAdmin->password = bcrypt($coach->password);
            $editedAdmin->faculty_id = $coach->email;
            $editedAdmin->save();

            $coach->save();
            return redirect()->route('coach.edit',$coach->id);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $test = User::where('id', Auth::id())->where('userType', 'admin')->count();
        $test2 = User::where('id', Auth::id())->where('userType', 'coach')->count();

        if($test == 0 && $test2 == 0)
        {
            $shit = User::where('id', Auth::id())->get();
            foreach ($shit as $a) {
                $pass = $a->faculty_id;
            }

            return redirect()->route('form.edit', Crypt::encrypt($pass));
        }
        else
        {
            $c=Coach::where('id',$id)->get()->first();

app/Http/Controllers/_CoachController.php
<?php

namespace App\Http\Controllers;

use App\Coach;
use App\Events;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Validator;

class CoachController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    } 
    public function index()
    {
        //
        $info=Coach::paginate(20);
        return view('coaches.index',compact('info'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

        return view('coaches.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $messages=array(

            'lname.required'=>'Last Name is Required',
            'fname.required'=>'First Name is Required',
            'age.required'=>'Age is Required',


        );
        $rules=array(
            'image'=>'required|image',

            'lname'=>'required',
            'fname'=>'required',
            'bday'=>'required',
            'age'=>'required',

            'address'=>'required',
            'email'=>'required'


        );
        $validator=Validator::make($request->all(),$rules,$messages)->validate();
        $coach=new Coach();

        if($request->hasFile('image')){
            $d=Carbon::now();
            $name=$request->get('lname').''.$d->day.str_random(4).$d->hour.$d->second;
            $p1='\images\\';
            $path= base_path() . '/public/images/';
            $request->file('image')->move($path,$name.'.'.$request->file('image')->getClientOriginalExtension());
            $coach->pic=$p1.$name.'.'.$request->file('image')->getClientOriginalExtension();
        }
        $coach->fill($request->all());
        $coach->save();
        return redirect()->route('coach.edit',$coach->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

        $events=Events::get();
        $info=Coach::where('id',$id)->get();
        if($info->count()) {
            $info=$info->first();
            $e = array();
            if ($info->events->count()) {
                foreach ($info->events as $pe) {
                    $e[$pe->name->first()->desc] = $pe->name->first()->desc;
                }
            }
            return view('coaches.edit', compact('info', 'events', 'e'));
        } else
            return redirect()->route('form.index')->with('messages','No Record Found');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $c=Coach::where('id',$id)->get()->first();
        $c->delete();
        $c->events()->delete();
        return redirect()->back();
    }
}

resources/views/coaches/edit.blade.php
<?php
    use App\User;
?>

@extends('layouts.app')

@section('content')
    <script>
        function ConfirmCreate()
        {
            var x = confirm("Are you sure of the information you entered?");
            if (x)
                return true;
            else
                return false;
        }
    </script>
    <div class="container">
        @if(count($errors)>=1)
            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-8">

                    @foreach($errors->all() as $c)
                        <span class="help-block">{{ $c }}</span>
                    @endforeach

                </div>
            </div>
            <br>
        @endif

        {{ Form::model($info, array('url'=>route('coach.update', $info->id), 'method'=>'PATCH', 'files'=>'true', 'onsubmit' => 'return ConfirmCreate()' )) }}
        <div class="row">
            <div class="col-md-8">&nbsp;</div>
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-2">
                <div class="form-group">
                    <img src="{{ $info->pic }}" class="img-responsive img-circle">
                    {{ Form::label('Upload Image') }}
                    {{ Form::file('image', null, array('class'=>'form-control')) }}
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="form-group">
				<div align="center"><h1>Coach Information</h1></div>
				</br>
                <div class="col-md-2">{{ Form::label('Name') }}</div>
                <div class="col-md-3">
                    {{ Form::text('lname', null, array('class'=>'form-control', 'placeholder'=>'Last Name')) }}
                </div>
                <div class="col-md-3">
                    {{ Form::text('fname', null, array('class'=>'form-control','placeholder'=>'First Name')) }}
                </div>
                <div class="col-md-3">
                    {{ Form::text('mname', null, array('class'=>'form-control','placeholder'=>'Middle Name')) }}
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="form-group">
                <div class="col-md-2">{{ Form::label('Birth date') }}</div>
                <div class="col-md-2">
                    {{ Form::date('bday', null,array('class'=>'form-control')) }}
                </div>
                <div class="col-md-1">{{ Form::label('Age') }}</div>
                <div class="col-md-2">
                    {{ Form::text('age', null, array('class'=>'form-control','placeholder'=>'Age', 'disabled')) }}
                </div>
                <div class="col-md-1">{{ Form::label('Email') }}</div>
                <div class="col-md-2">
                    {{ Form::text('email', null, array('class'=>'form-control', 'placeholder'=>'E-mail')) }}
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="form-group">
                <div class="col-md-2">{{ Form::label('Address') }}</div>
                <div class="col-md-4">
                    {{ Form::text('address', null, array('class'=>'form-control', 'placeholder'=>'Address')) }}
                </div>
                <div class="col-md-1">{{ Form::label('Contact #') }}</div>
                <div class="col-md-4">
                    {{ Form::text('contact', null, array('class'=>'form-control', 'placeholder'=>'Contact Number')) }}
                </div>
            </div>
        </div>
        @if( ( (User::where('id', Auth::id())->get()->first()->faculty_id) == $info->email) || (User::where('id', Auth::id())->get()->first()->userType) == 'admin')
        <br>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-2">{{ Form::label('Password') }}</div>
                    <div class="col-md-2">
                        <input id="password" type="password" class="form-control" name="password" value="{{ $info->password }}" required>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-2">
                        
                    </div>
                </div>
            </div>
        @else
            {{ Form::hidden('password', $info->password) }}
        @endif
        <br>
        <br>
        <div class="row">
            <div class="col-md-10">&nbsp;</div>
            <div class="col-md-2">
                {{ Form::submit('Save Information', array('class'=>'btn btn-success')) }}
            </div>
        </div>
        <script>
            function ConfirmDelete()
            {
                var x = confirm("Are you sure you want to delete?");
                if (x)
                    return true;
                else
                    return false;
            }
        </script>
        {{ Form::close() }}
        {{ Form::open(array('url'=>route('coach.destroy', $info->id), 'method'=>'DELETE', 'onsubmit' => 'return ConfirmDelete()')) }}
            
        {{ Form::close() }}
        <div class="row">
            <div class="col-md-12">
			<hr/>
			<div align="center"><h1>Event Information</h1></div>
				</br>
                <table class="table table-striped table-responsive table-condensed">
                    <thead>
                        <tr>
                            <td>&nbsp;</td>
                            <td>Event</td>
                            <td>Status</td>
                            <td>&nbsp;</td>
                        </tr>
                    </thead>

                    @if($info->events->count())
                        @foreach($info->events as $e)
                            <tr>
                                <td>&nbsp;</td>
                                <td>{{ $e->name->desc }}</td>
                                <td>
                                    {{ Form::select('status', array(1=>'Head Coach', 2=>'Asst. Coach', 3=>'Coach 1', 4=>'Coach 2'), $e->status, array('class'=>'form-control', 'disabled')) }}
                                </td>
								<td>&nbsp;</td>
                                <td width="3">
                                    {{ Form::open(array('url'=>route('evet2', $e->name->id), 'method'=>'GET')) }}
                                        {{ Form::submit('Show', array('class'=>'btn btn-success')) }}
                                    {{ Form::close() }}
                                </td>
                                <td width="3">
                                    {{ Form::open(array('url'=>route('ce.destroy', $e->id), 'method'=>'DELETE')) }}
                                        {{ Form::submit('Delete', array('class'=>'btn btn-danger')) }}
                                    {{ Form::close() }}
                                </td>
                            </tr>
                        @endforeach
                    @endif

                        <tr>
                            <td>&nbsp;</td>
                            {{ Form::open(array('url'=>route('ce.store'), 'method'=>'POST', 'onsubmit' => 'return ConfirmCreate()')) }}
                            <td>
                                {{ Form::hidden('coach_id', $info->id) }}
                                {{ Form::select('event', $events->pluck('desc', 'id'), null, array('class' => 'form-control')) }}
                            </td>
                            <td>
                                {{ Form::select('status', array(1=>'Head Coach', 2=>'Asst. Coach', 3=>'Coach 1', 4=>'Coach 2'), null, array('class'=>'form-control')) }}
                            </td>
							<td width="3">&nbsp;</td>
							<td width="3">&nbsp;</td>
                            <td width="3">
                                {{ Form::submit('Add Event', array('class'=>'btn btn-success')) }}
                            </td>
                            {{ Form::close() }}
                      </tr>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/coaches/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if(\Illuminate\Support\Facades\Session::has('messages'))
            <div class="row">
                <div class="col-md-2">&nbsp;</div>
                <div class="col-sm-8 alert alert-danger">
                    <center><span >{{ \Illuminate\Support\Facades\Session::get('messages') }}</span></center>
                </div>
            </div>
        @endif

        <div class="row">
            {{ Form::open(array('url'=>route('eve'), 'method'=>'POST')) }}
            {{ csrf_field() }}
            <div class="form-group"></div>
            {{ csrf_field() }}
            {{ Form::close() }}
            <div class="col-md-2">&nbsp;</div>
            {{ Form::open(array('url'=>route('ser'), 'method'=>'POST')) }}
            {{ csrf_field() }}
            <div class="col-md-12" align="right">
                <a href="{{ route('coach.create') }}" class='btn btn-primary'>Add Coach Information</a>
            </div>
            {{csrf_field()}}
            {{Form::close()}}
        </div>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-responsive table-condensed">
                    <thead>
                    <td>Name</td>
                    <td>&nbsp;</td>
                    </thead>
                    <script>
                        function ConfirmDelete()
                        {
                            var x = confirm("Are you sure you want to delete?");
                            if (x)
                                return true;
                            else
                                return false;
                        }
                    </script>
                    @foreach($info as $i)
                        <tr>
                            <td class="text-uppercase">{{ $i->lname }}, {{ $i->fname }} {{ $i->mname }}</td>
                            <td width="3">
                                {{ Form::open(array('url'=>route('coach.edit', $i->id), 'method'=>'GET')) }}
                                {{ csrf_field() }}
                                <button type="submit" class="glyphicon glyphicon-edit"></button>
                                {{ csrf_field() }}
                                {{ Form::close() }}
                            </td>
                            <td width="3">
                                {{ Form::open(array('url'=>route('coach.destroy', $i->id), 'method'=>'DELETE', 'onsubmit' => 'return ConfirmDelete()')) }}
                                {{ csrf_field() }}
                                <button type="submit" class="glyphicon glyphicon-trash"></button>
                                {{ csrf_field() }}
                                {{ Form::close() }}
                            </td>
                            
                        </tr>
                    @endforeach

                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">&nbsp;</div>
            <div class="col-md-8" align="center">{{ $info->links() }}</div>
        </div>
    </div>
@endsection